platform :ios, '10.0'

target 'ios-recruit-challenge' do
  use_frameworks!

    pod 'AlamofireImage', '~> 3.3'
    pod 'DRPLoadingSpinner', '~> 1.3'
    pod 'AlamofireObjectMapper', '~> 5.0'
    pod 'OHHTTPStubs/Swift'

    target 'ios-recruit-challengeTests' do
        inherit! :search_paths
        
        pod 'OHHTTPStubs/Swift'
    end
    
    target 'ios-recruit-challengeUITests' do
        pod 'OHHTTPStubs/Swift'
    end

end
